[package]
name = "examine-error-details"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
google-cloud-gax.workspace = true
google-cloud-language-v2.workspace = true
tokio.workspace = true
