[package]
name = "error-handling"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
crc32c.workspace = true
google-cloud-gax.workspace = true
google-cloud-secretmanager-v1.workspace = true
tokio.workspace = true
