[package]
name = "cloud-storage"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes.workspace = true
google-cloud-storage.workspace = true
tokio.workspace = true
uuid.workspace = true

[[bin]]
name = "quickstart"
path = "src/quickstart.rs"
